/* Ngân hàng dùng chung cho bản Next.js và file HTML độc lập. */
const TOEIC_QUESTION_BANK = [
  [
    {
      focus: 'Part 2 · Paraphrase', difficulty: '750+',
      prompt: 'The shipment is expected to arrive ahead of schedule.',
      options: ['The delivery will be late.', 'The delivery may arrive early.', 'The order was canceled.', 'The schedule is unavailable.'], answer: 1,
      translation: 'Lô hàng được dự kiến sẽ đến sớm hơn lịch trình.',
      explanation: 'Đáp án B diễn đạt lại chính xác “ahead of schedule” bằng “arrive early”. TOEIC thường không lặp nguyên từ khóa mà đổi sang một cụm đồng nghĩa.',
      rule: 'ahead of schedule = earlier than planned; behind schedule = later than planned.',
      trap: 'Bẫy trái nghĩa: “late” nghe liên quan đến thời gian nhưng đảo ngược hoàn toàn ý của câu.',
      choiceNotes: ['A sai: “late” trái nghĩa với “ahead of schedule”.', 'B đúng: “may arrive early” là cách paraphrase tự nhiên.', 'C sai: câu không hề đề cập việc hủy đơn.', 'D sai: lịch trình có tồn tại và đang được dùng làm mốc so sánh.'],
    },
    {
      focus: 'Part 2 · WH-question', difficulty: '700+',
      prompt: 'Why was the conference room reservation changed?',
      options: ['At the front desk.', 'Because the larger room became available.', 'For about two hours.', 'Yes, I made a reservation.'], answer: 1,
      translation: 'Tại sao việc đặt phòng hội nghị lại được thay đổi?',
      explanation: '“Why” yêu cầu nguyên nhân. Chỉ đáp án B cung cấp lý do bằng mệnh đề bắt đầu với “Because”.',
      rule: 'Why → reason; Where → place; How long → duration. Xác định loại thông tin trước khi nghe đáp án.',
      trap: 'Bẫy từ lặp: đáp án D lặp lại “reservation” nhưng không trả lời lý do.',
      choiceNotes: ['A trả lời địa điểm, phù hợp với “Where”.', 'B trả lời nguyên nhân trực tiếp.', 'C trả lời khoảng thời gian, phù hợp với “How long”.', 'D chỉ xác nhận đã đặt phòng, không giải thích thay đổi.'],
    },
    {
      focus: 'Part 2 · Indirect response', difficulty: '800+',
      prompt: 'Would you mind sending me the revised sales figures?',
      options: ['Not at all. I’ll email them now.', 'The sales team is upstairs.', 'It was revised yesterday.', 'About thirty figures.'], answer: 0,
      translation: 'Bạn có phiền gửi cho tôi số liệu bán hàng đã chỉnh sửa không?',
      explanation: '“Would you mind + V-ing?” là lời nhờ lịch sự. “Not at all” mang nghĩa “Không phiền đâu”, sau đó người nói xác nhận sẽ gửi ngay.',
      rule: 'Với “Would you mind...?”, “No/Not at all” là đồng ý; “Yes” thường mang nghĩa có phiền.',
      trap: 'Bẫy logic: người học dễ hiểu “Not at all” là từ chối vì thấy phủ định.',
      choiceNotes: ['A đúng: đồng ý lời nhờ và nêu hành động.', 'B chỉ nói vị trí của đội bán hàng.', 'C dùng sai chủ thể: “figures” số nhiều phải là “they”.', 'D hiểu “figures” thành con số đếm được, không phù hợp ngữ cảnh.'],
    },
    {
      focus: 'Part 3 · Intent', difficulty: '850+',
      prompt: 'I can cover the morning shift, but I have a client meeting after lunch.',
      options: ['The speaker is available all day.', 'The speaker can work only in the morning.', 'The client canceled the meeting.', 'The morning shift has been canceled.'], answer: 1,
      translation: 'Tôi có thể trực ca sáng, nhưng sau bữa trưa tôi có cuộc họp với khách hàng.',
      explanation: 'Liên từ “but” giới hạn sự sẵn sàng của người nói. Người nói nhận ca sáng nhưng bận vào buổi chiều, nên B là kết luận chính xác.',
      rule: 'Trong Part 3, thông tin sau “but/however” thường là điều kiện quyết định đáp án.',
      trap: 'Bẫy suy diễn quá mức: có cuộc họp không có nghĩa cuộc họp bị hủy hay ca sáng bị hủy.',
      choiceNotes: ['A sai vì người nói bận sau bữa trưa.', 'B đúng: chỉ có thể làm ca sáng.', 'C không có thông tin về việc hủy họp.', 'D người nói đang nhận ca sáng, không phải hủy ca.'],
    },
    {
      focus: 'Part 2 · Suggestion', difficulty: '800+',
      prompt: 'Why don’t we postpone the product launch until the website is ready?',
      options: ['It was launched online.', 'That would give us more time to test it.', 'The website designer is Ms. Park.', 'At the end of the hallway.'], answer: 1,
      translation: 'Sao chúng ta không hoãn ra mắt sản phẩm cho đến khi trang web sẵn sàng?',
      explanation: '“Why don’t we...?” là lời đề nghị, không phải câu hỏi nguyên nhân. B phản hồi trực tiếp bằng cách nêu lợi ích của đề nghị đó.',
      rule: 'Why don’t we + V = Let’s + V. Đáp án thường đồng ý, phản đối hoặc đưa ra điều kiện.',
      trap: 'Bẫy hình thức: thấy “Why” rồi tìm câu trả lời bắt đầu bằng “Because”.',
      choiceNotes: ['A sai thì và không phản hồi đề nghị.', 'B đúng: đồng tình và nêu lợi ích.', 'C chỉ cung cấp tên người thiết kế.', 'D trả lời vị trí, hoàn toàn lệch loại thông tin.'],
    },
    {
      focus: 'Part 4 · Announcement', difficulty: '850+',
      prompt: 'Passengers for Flight 672 should proceed to Gate 14 instead of Gate 9.',
      options: ['The flight has been delayed.', 'The departure gate has changed.', 'Passengers should collect their luggage.', 'Flight 672 will leave from Gate 9.'], answer: 1,
      translation: 'Hành khách chuyến bay 672 nên đến Cổng 14 thay vì Cổng 9.',
      explanation: 'Cụm “instead of” báo hiệu một thay đổi: cổng mới là 14, thay cho cổng cũ 9. B tóm tắt đúng thông báo.',
      rule: 'instead of A = thay cho A. Thông tin ngay trước cụm này thường là thông tin mới cần làm theo.',
      trap: 'Bẫy con số: đáp án D dùng đúng số cổng được nghe nhưng đó là cổng cũ.',
      choiceNotes: ['A không có từ nào nói chuyến bay trễ.', 'B đúng: cổng khởi hành đã đổi.', 'C không đề cập hành lý.', 'D sai vì Gate 9 đã được thay bằng Gate 14.'],
    },
  ],
  [
    {
      focus: 'Part 5 · Preposition', difficulty: '700+',
      prompt: 'All employees are required to submit travel receipts _____ ten business days.',
      options: ['within', 'during', 'among', 'beside'], answer: 0,
      translation: 'Tất cả nhân viên phải nộp biên lai công tác trong vòng mười ngày làm việc.',
      explanation: '“Within + khoảng thời gian” đặt ra hạn chót: việc nộp phải hoàn tất trước khi mười ngày kết thúc.',
      rule: 'within + duration; during + event/period (during the conference); by + deadline (by Friday).',
      trap: 'Bẫy giới từ thời gian: “during” cũng liên quan thời gian nhưng không đi tự nhiên với một khoảng đếm để diễn tả hạn chót.',
      choiceNotes: ['A đúng: trong vòng mười ngày.', 'B sai: thường cần một sự kiện hoặc giai đoạn có tên.', 'C sai: “among” dùng giữa một nhóm.', 'D sai: “beside” chỉ vị trí bên cạnh.'],
    },
    {
      focus: 'Part 5 · Conjunction vs. preposition', difficulty: '800+',
      prompt: 'The board approved the proposal _____ several concerns about its cost.',
      options: ['although', 'despite', 'because', 'unless'], answer: 1,
      translation: 'Hội đồng đã thông qua đề xuất mặc dù có một số lo ngại về chi phí.',
      explanation: 'Sau chỗ trống là cụm danh từ “several concerns”, vì vậy cần giới từ “despite”. “Although” phải đứng trước một mệnh đề có chủ ngữ và động từ.',
      rule: 'despite/in spite of + noun/V-ing; although/even though + subject + verb.',
      trap: 'Bẫy nghĩa giống, cấu trúc khác: “although” và “despite” đều chỉ nhượng bộ nhưng không thay thế nhau về ngữ pháp.',
      choiceNotes: ['A sai cấu trúc vì phía sau không phải mệnh đề.', 'B đúng cả nghĩa lẫn cấu trúc.', 'C sai nghĩa: lo ngại không phải lý do khiến đề xuất được duyệt.', 'D cần một mệnh đề điều kiện phía sau.'],
    },
    {
      focus: 'Part 5 · Word form', difficulty: '750+',
      prompt: 'Ms. Tran is responsible for ensuring that all reports are _____ prepared.',
      options: ['accuracy', 'accurate', 'accurately', 'accurateness'], answer: 2,
      translation: 'Bà Trần chịu trách nhiệm đảm bảo tất cả báo cáo được chuẩn bị chính xác.',
      explanation: '“Prepared” là quá khứ phân từ đóng vai trò động từ trong câu bị động. Ta cần trạng từ “accurately” để bổ nghĩa cho cách các báo cáo được chuẩn bị.',
      rule: 'be + adverb + past participle: be carefully reviewed, be properly installed.',
      trap: 'Bẫy từ loại: “accurate” thường đứng sau “be”, nhưng ở đây “are prepared” là cả cụm động từ và cần trạng từ chen giữa.',
      choiceNotes: ['A là danh từ.', 'B là tính từ.', 'C là trạng từ và bổ nghĩa đúng cho “prepared”.', 'D là danh từ hiếm dùng và không phù hợp vị trí.'],
    },
    {
      focus: 'Part 5 · Subject–verb agreement', difficulty: '800+',
      prompt: 'Neither the regional managers nor the director _____ available for comment yesterday.',
      options: ['were', 'was', 'are', 'have been'], answer: 1,
      translation: 'Hôm qua, cả các quản lý khu vực lẫn giám đốc đều không sẵn sàng bình luận.',
      explanation: 'Với “neither A nor B”, động từ hòa hợp với chủ ngữ gần nhất. “The director” số ít nên dùng “was”; “yesterday” xác định thì quá khứ.',
      rule: 'either A or B / neither A nor B → động từ theo B, tức chủ ngữ gần động từ nhất.',
      trap: 'Bẫy khoảng cách: “regional managers” số nhiều xuất hiện trước khiến người học chọn “were”.',
      choiceNotes: ['A sai vì chủ ngữ gần nhất “director” số ít.', 'B đúng về hòa hợp và thì.', 'C sai thì vì có “yesterday”.', 'D sai cả cấu trúc số ít lẫn thì phù hợp.'],
    },
    {
      focus: 'Part 5 · Reduced relative clause', difficulty: '850+',
      prompt: 'Customers _____ in the loyalty program receive early access to promotions.',
      options: ['enroll', 'enrolled', 'enrolling', 'enrollment'], answer: 1,
      translation: 'Khách hàng đã đăng ký chương trình khách hàng thân thiết được tiếp cận sớm các chương trình khuyến mãi.',
      explanation: '“Enrolled in...” là mệnh đề quan hệ bị động rút gọn từ “who are enrolled in...”. Khách hàng là đối tượng được ghi danh, nên dùng V3.',
      rule: 'noun + V3 = noun + who/which is/are + V3 khi mang nghĩa bị động.',
      trap: 'Bẫy chủ động/bị động: “enrolling” sẽ gợi khách hàng đang tự thực hiện hành động lên một đối tượng khác.',
      choiceNotes: ['A là động từ nguyên mẫu, tạo hai động từ chính.', 'B đúng: mệnh đề bị động rút gọn.', 'C không phù hợp quan hệ nghĩa.', 'D là danh từ, không thể bổ nghĩa trực tiếp theo cấu trúc này.'],
    },
    {
      focus: 'Part 6 · Connector', difficulty: '850+',
      prompt: 'The software update improves security. _____, it reduces the time needed to process orders.',
      options: ['In addition', 'Nevertheless', 'For instance', 'Otherwise'], answer: 0,
      translation: 'Bản cập nhật phần mềm cải thiện bảo mật. Ngoài ra, nó còn giảm thời gian xử lý đơn hàng.',
      explanation: 'Hai câu cùng liệt kê hai lợi ích bổ sung của bản cập nhật, vì vậy “In addition” tạo quan hệ cộng thêm.',
      rule: 'in addition = thêm ý; nevertheless = tương phản; for instance = ví dụ; otherwise = nếu không thì.',
      trap: 'Bẫy liên từ trang trọng: mọi lựa chọn đều có thể đứng đầu câu nhưng chỉ một từ tạo đúng quan hệ logic.',
      choiceNotes: ['A đúng: thêm một lợi ích cùng chiều.', 'B sai vì không có sự tương phản.', 'C sai vì câu sau không phải ví dụ của “security”.', 'D sai vì không có quan hệ điều kiện/hậu quả.'],
    },
  ],
  [
    {
      focus: 'Speaking · Customer service', difficulty: '750+',
      prompt: 'A client says: “The replacement still hasn’t arrived.” What is the best response?',
      options: ['You should wait.', 'That is not my department.', 'I’m sorry about the delay. Let me check the shipment now.', 'Replacements are usually blue.'], answer: 2,
      translation: 'Khách hàng nói: “Hàng thay thế vẫn chưa tới.” Hãy chọn phản hồi tốt nhất.',
      explanation: 'C đáp ứng đủ ba bước của phản hồi dịch vụ chuyên nghiệp: xin lỗi, xác nhận vấn đề và đề xuất hành động ngay.',
      rule: 'Acknowledge → Apologize → Act: xác nhận → xin lỗi → đưa ra giải pháp cụ thể.',
      trap: 'Bẫy phản hồi ngắn: câu đúng ngữ pháp chưa chắc đạt điểm cao nếu lạnh lùng hoặc không giải quyết vấn đề.',
      choiceNotes: ['A thiếu lịch sự và không có giải pháp.', 'B đẩy trách nhiệm sang bộ phận khác.', 'C chuyên nghiệp, chủ động và cụ thể.', 'D không liên quan đến việc giao hàng chậm.'],
    },
    {
      focus: 'Speaking · Presentation', difficulty: '800+',
      prompt: 'Which opening sounds most professional in a presentation?',
      options: ['Hey guys, so...', 'Today, I’d like to outline three ways we can improve customer retention.', 'You know what I mean?', 'I have no idea where to start.'], answer: 1,
      translation: 'Câu mở đầu nào chuyên nghiệp nhất trong một bài thuyết trình?',
      explanation: 'B nêu chủ đề, báo trước cấu trúc “three ways” và sử dụng giọng điệu công sở phù hợp. Người nghe biết ngay điều gì sắp được trình bày.',
      rule: 'Mở bài điểm cao: purpose + scope/structure. Ví dụ: “I’d like to explain...” + số ý chính.',
      trap: 'Bẫy văn nói: các filler như “so”, “you know” tự nhiên trong hội thoại nhưng làm bài nói thiếu kiểm soát.',
      choiceNotes: ['A quá thân mật và có filler.', 'B rõ mục tiêu và cấu trúc.', 'C là filler, không cung cấp nội dung.', 'D thể hiện thiếu chuẩn bị.'],
    },
    {
      focus: 'Speaking · Recommendation', difficulty: '850+',
      prompt: 'Choose the strongest recommendation.',
      options: ['Maybe do something about costs.', 'Costs are bad.', 'I recommend renegotiating our supplier contracts to reduce costs by next quarter.', 'Suppliers exist.'], answer: 2,
      translation: 'Chọn lời đề xuất thuyết phục nhất.',
      explanation: 'C có động từ đề xuất rõ ràng, hành động cụ thể, mục tiêu và thời hạn. Đây là cấu trúc giúp câu trả lời có chiều sâu thay vì chỉ nêu ý kiến.',
      rule: 'I recommend + V-ing + because/to + benefit + timeframe.',
      trap: 'Bẫy nội dung mơ hồ: nhắc đúng chủ đề “costs” không đủ nếu thiếu hành động và lý do.',
      choiceNotes: ['A mơ hồ: “something” không thể hành động.', 'B chỉ mô tả vấn đề.', 'C đầy đủ giải pháp, mục tiêu và hạn.', 'D là một sự thật không tạo lập luận.'],
    },
    {
      focus: 'Speaking · Opinion support', difficulty: '800+',
      prompt: 'Which answer best supports the opinion that remote work should continue?',
      options: ['I like it.', 'Remote work is remote.', 'It reduces commuting time, and employees can use that time to focus on priority tasks.', 'Many offices have desks.'], answer: 2,
      translation: 'Câu nào hỗ trợ tốt nhất cho ý kiến nên tiếp tục làm việc từ xa?',
      explanation: 'C không chỉ nêu lợi ích mà còn giải thích chuỗi nguyên nhân–kết quả: giảm thời gian đi lại → thêm thời gian cho công việc ưu tiên.',
      rule: 'Opinion → reason → consequence/example. Một lý do được phát triển tốt hơn hai lý do chỉ liệt kê.',
      trap: 'Bẫy ý kiến cá nhân trống: “I like it” có lập trường nhưng không có bằng chứng.',
      choiceNotes: ['A thiếu lý do.', 'B lặp từ mà không có ý nghĩa.', 'C có lý do và hệ quả cụ thể.', 'D đúng sự thật nhưng không liên quan lập trường.'],
    },
    {
      focus: 'Speaking · Polite interruption', difficulty: '850+',
      prompt: 'You need to clarify a figure during a meeting. Which phrase is best?',
      options: ['Stop. That number is wrong.', 'Sorry to interrupt, but could you clarify whether that figure includes tax?', 'What are you talking about?', 'The figure is a figure.'], answer: 1,
      translation: 'Bạn cần làm rõ một con số trong cuộc họp. Cách nói nào phù hợp nhất?',
      explanation: 'B dùng cụm giảm nhẹ “Sorry to interrupt” và câu hỏi gián tiếp “could you clarify whether...”, vừa lịch sự vừa nêu đúng điểm cần xác nhận.',
      rule: 'Polite interruption: Sorry to interrupt, but could you clarify/confirm...?',
      trap: 'Bẫy trực tiếp quá mức: trong môi trường công sở, đúng nội dung nhưng sai register vẫn làm giảm chất lượng câu trả lời.',
      choiceNotes: ['A mang tính đối đầu và kết luận khi chưa xác minh.', 'B lịch sự, cụ thể và trung lập.', 'C thô và mơ hồ.', 'D không yêu cầu thông tin.'],
    },
    {
      focus: 'Speaking · Compare options', difficulty: '900+',
      prompt: 'Which response compares two venues most effectively?',
      options: ['Venue A is good. Venue B is also a venue.', 'I choose A.', 'Although Venue A is cheaper, Venue B is closer to public transit, so it would be more convenient for attendees.', 'Both have rooms.'], answer: 2,
      translation: 'Phản hồi nào so sánh hai địa điểm hiệu quả nhất?',
      explanation: 'C dùng “although” để cân hai tiêu chí, sau đó đưa ra kết luận dựa trên lợi ích cho người tham dự. Cấu trúc này thể hiện khả năng phát triển lập luận.',
      rule: 'Although A has X, B has Y, so I would choose B because Z.',
      trap: 'Bẫy lựa chọn không biện minh: nêu “I choose A” không chứng minh khả năng so sánh.',
      choiceNotes: ['A không có tiêu chí so sánh hữu ích.', 'B có lựa chọn nhưng thiếu lý do.', 'C so sánh, nhượng bộ và kết luận logic.', 'D chỉ nêu điểm giống nhau hiển nhiên.'],
    },
  ],
  [
    {
      focus: 'Writing · Concision', difficulty: '750+',
      prompt: 'Choose the clearest business sentence.',
      options: ['Due to the fact that demand increased, we hired.', 'Because demand increased, we hired two additional agents.', 'Demand increased and stuff happened.', 'Hiring, because of demand, maybe.'], answer: 1,
      translation: 'Chọn câu văn công sở rõ ràng nhất.',
      explanation: 'B thay cụm dài “due to the fact that” bằng “because” và nêu kết quả cụ thể “two additional agents”. Câu vừa gọn vừa đủ thông tin.',
      rule: 'Ưu tiên động từ mạnh, con số cụ thể và liên từ ngắn. due to the fact that → because.',
      trap: 'Bẫy trang trọng giả: câu dài hơn không đồng nghĩa với chuyên nghiệp hơn.',
      choiceNotes: ['A dài dòng và thiếu số lượng tuyển.', 'B súc tích, cụ thể, đúng quan hệ nguyên nhân.', 'C dùng “stuff” quá mơ hồ.', 'D là mảnh câu và có “maybe” làm yếu thông điệp.'],
    },
    {
      focus: 'Writing · Formal tone', difficulty: '800+',
      prompt: 'Which sentence uses the correct tone for a complaint email?',
      options: ['Your service is terrible!', 'Fix this now.', 'Could you please review the attached invoice and correct the duplicate charge?', 'Whatever, I paid twice.'], answer: 2,
      translation: 'Câu nào có giọng điệu phù hợp cho email khiếu nại?',
      explanation: 'C giữ giọng trung lập, chỉ rõ tài liệu cần kiểm tra và hành động mong muốn. Lịch sự không làm yêu cầu kém dứt khoát.',
      rule: 'Complaint email: factual problem + polite request + desired resolution.',
      trap: 'Bẫy cảm xúc: dấu chấm than và mệnh lệnh có thể thể hiện bức xúc nhưng làm giảm tính chuyên nghiệp.',
      choiceNotes: ['A công kích chung chung.', 'B là mệnh lệnh thiếu lịch sự.', 'C nêu vấn đề và yêu cầu cụ thể.', 'D quá khẩu ngữ và thiếu giải pháp.'],
    },
    {
      focus: 'Writing · Transition', difficulty: '800+',
      prompt: 'The campaign increased traffic. _____, conversion rates remained unchanged.',
      options: ['However', 'For example', 'Therefore', 'Similarly'], answer: 0,
      translation: 'Chiến dịch làm tăng lượt truy cập. Tuy nhiên, tỷ lệ chuyển đổi không thay đổi.',
      explanation: 'Lượt truy cập tăng tạo kỳ vọng kết quả tốt hơn, nhưng conversion không đổi. “However” đánh dấu sự tương phản với kỳ vọng đó.',
      rule: 'however = contrast; therefore = result; for example = illustration; similarly = similarity.',
      trap: 'Bẫy quan hệ nhân quả: hai câu cùng nói về chiến dịch nhưng không có nghĩa câu sau là kết quả của câu trước.',
      choiceNotes: ['A đúng: quan hệ tương phản.', 'B sai: câu sau không phải ví dụ.', 'C sai: conversion không đổi không phải hệ quả logic của traffic tăng.', 'D sai: hai kết quả không tương đồng.'],
    },
    {
      focus: 'Writing · Parallel structure', difficulty: '850+',
      prompt: 'Choose the sentence with correct parallel structure.',
      options: ['The role involves scheduling meetings, to prepare reports, and client communication.', 'The role involves scheduling meetings, preparing reports, and communicating with clients.', 'The role involves schedule meetings, reports, and to communicate.', 'The role involving meetings and prepared reports.'], answer: 1,
      translation: 'Chọn câu có cấu trúc song song chính xác.',
      explanation: 'Ba nhiệm vụ trong B đều dùng dạng V-ing: “scheduling, preparing, communicating”. Các thành phần cùng chức năng phải có cùng dạng ngữ pháp.',
      rule: 'A, B, and C phải song song: V-ing/V-ing/V-ing hoặc to V/to V/to V.',
      trap: 'Bẫy danh sách: người đọc hiểu được ý nên dễ bỏ qua việc các thành phần đang dùng ba dạng khác nhau.',
      choiceNotes: ['A trộn V-ing, to V và danh từ.', 'B đúng: ba động danh từ song song.', 'C trộn nguyên mẫu, danh từ và to V.', 'D thiếu động từ chính hoàn chỉnh.'],
    },
    {
      focus: 'Writing · Email purpose', difficulty: '850+',
      prompt: 'Which opening states the purpose of an email most clearly?',
      options: ['Hello, I hope everything is fine and many things are happening.', 'I am writing to confirm our delivery schedule for the May 18 order.', 'About that thing we discussed...', 'This email is an email about delivery.'], answer: 1,
      translation: 'Câu mở đầu nào nêu mục đích email rõ nhất?',
      explanation: 'B dùng mẫu “I am writing to...” và định danh chính xác đối tượng bằng ngày của đơn hàng. Người nhận hiểu ngay lý do cần đọc email.',
      rule: 'I am writing to + action + specific reference/order/date.',
      trap: 'Bẫy mở đầu xã giao quá dài: lời chào có thể có, nhưng không được thay thế câu nêu mục đích.',
      choiceNotes: ['A dài nhưng không có mục đích.', 'B rõ hành động và đơn hàng liên quan.', 'C dùng đại từ mơ hồ “that thing”.', 'D lặp từ và vẫn thiếu thông tin cụ thể.'],
    },
    {
      focus: 'Writing · Data description', difficulty: '900+',
      prompt: 'Which sentence describes the data most precisely?',
      options: ['Sales went up a lot.', 'Sales were nice in June.', 'Online sales rose by 18 percent from May to June, while in-store sales remained stable.', 'There were sales and percentages.'], answer: 2,
      translation: 'Câu nào mô tả dữ liệu chính xác nhất?',
      explanation: 'C cung cấp kênh bán, mức thay đổi, khoảng thời gian và phép so sánh. Đây là bốn mảnh thông tin giúp mô tả biểu đồ đạt điểm cao.',
      rule: 'Data sentence: subject + trend verb + amount + period, while + comparison.',
      trap: 'Bẫy tính từ cảm tính: “a lot/nice” không đo lường được và không thể hiện độ chính xác.',
      choiceNotes: ['A thiếu con số và mốc thời gian.', 'B dùng “nice” không phải ngôn ngữ dữ liệu.', 'C cụ thể và có so sánh.', 'D không truyền tải xu hướng nào.'],
    },
  ],
];

if (typeof window !== 'undefined') window.TOEIC_QUESTION_BANK = TOEIC_QUESTION_BANK;
if (typeof module !== 'undefined') module.exports = TOEIC_QUESTION_BANK;
